### ISSUE TITLE
daemon-scheduler constraint doesn't hold in manual start of the container

### ISSUE THREAD

**Issue by wliao008** [blox/blox#92] opened 2016-12-12 20:56 UTC
I was testing daemon-scheduler locally and observed this behavior:

* I created an environment and deployment for the daemon-scheduler. The service involved in ECS currently has 0 container running. There are 3 hosts.
* The daemon deployed and 1 copy of the container is running on each host.
* I ssh'd onto one of the hosts, killed the container, looking at the log, as expected, a new one got started. Also worked when I added a new host to the cluster. 
* I manually started a container of the same service on one of the hosts, and both containers continue to run. Here I (kinda) expect the daemon would step in and enforce the constraint by removing one?
* I killed off the container (started by the daemon) and leave the one (started by me) running, a new one got started by the daemon again, and 2 copies are still running.

Is my assumption of how this should work wrong?

**Comment by poojamaiya** [comment] 2016-12-12 21:11
>> I manually started a container of the same service on one of the hosts, and both containers continue to run. Here I (kinda) expect the daemon would step in and enforce the constraint by removing one?

This is the expected behavior. Daemon scheduler works independently in that it is not affected by other tasks already running or launched by any other process. It will launch tasks even though there is a task already running (if the task is not launched by it).

>>I killed off the container (started by the daemon) and leave the one (started by me) running, a new one got started by the daemon again, and 2 copies are still running.

Again, this is the expected behavior. On the other hand, if you had killed the task started manually by you and left the task started by the daemon scheduler as is, the scheduler would not have kicked off the new task.

Please let us know if this does not make sense or if you have more questions, we'd be happy to clarify.

**Comment by wliao008** [comment] 2016-12-12 21:43
I suspect that might be the case, since the service desired count has no effect as well, and it could be challenging to get that to work with the daemon scheduler. I was really shooting for the constraint to be strictly enforced per host, is there any chance of having this type of constraint built-in to ECS?

**Comment by narehayrapetyan** [comment] 2016-12-13 01:46
It is not safe for the daemon scheduler to kill and/or restart tasks that are not started by it since it has no knowledge of what they are.

Can you clarify what you mean by "the service desired count has no effect as well, and it could be challenging to get that to work with the daemon scheduler."

**Comment by wliao008** [comment] 2016-12-13 14:20
By that, I meant the desired count of the service in the ECS cluster, where I scale up and down as needed. As you mentioned, that's independent of and doesn't affect the daemon-scheduler, which makes sense. It'd be challenging (and probably won't make sense) to have the daemon honor the service count.

If the above isn't solved, while we could still make the daemon-scheduler work reasonably well, there is really no guarantee only one copy is running per host, which is why I was suggesting it'd be nice if ECS supports this natively.

**Comment by narehayrapetyan** [comment] 2016-12-14 20:02
@wliao008 what is your use case for manually running tasks in your cluster?

**Comment by wliao008** [comment] 2016-12-14 20:30
@narehayrapetyan for my setup, I set the service desired count to be 0, and have daemon-scheduler start up the containers on each host, that give me 1 container per host. I could easily see somewhere down the road, people is going to come in and notice "hey why is the desired count 0? it should be xx", then boom we'd end up with multiple copies. While manually starting the container is probably a moo point, I was more of testing of ways that could potentially mess up the deployment.

**Comment by poojamaiya** [comment] 2016-12-23 00:43
@wliao008 the daemon scheduler should not interfere with tasks started by other processes (schedulers, applications, etc.). With the use-case you mentioned, we'd expect the users of the daemon scheduler to not manually launch tasks on behalf of it. We do not think that it is a valid use case from the perspective of using the daemon scheduler. We're closing this issue in favor of not supporting the use-case. Please feel free to re-open if you disagree or have more questions.

**Closed by poojamaiya** 2016-12-23 00:43 UTC
