### ISSUE TITLE
Flaky Test?

### ISSUE THREAD

**Issue by jhspaybar** [blox/blox#83] opened 2016-12-07 08:00 UTC
I'm still new to Go and the testing framework being used, but sometimes when I run `make` it will fail with 1 error and this looks like it might be related.

```
--- PASS: TestRunLoadInstancesReturnsError (0.00s)
panic: Fail in goroutine after TestOverlappingRunInvocationsAreSkipped has completed

goroutine 9 [running]:
panic(0x51cce0, 0xc42016e910)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.(*common).Fail(0xc4200a4540)
	/usr/local/go/src/testing/testing.go:412 +0x11f
testing.(*common).FailNow(0xc4200a4540)
	/usr/local/go/src/testing/testing.go:431 +0x2b
testing.(*common).Fatalf(0xc4200a4540, 0x5fef7b, 0x24, 0xc4201a6390, 0x3, 0x3)
	/usr/local/go/src/testing/testing.go:496 +0x83
github.com/blox/blox/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc42027f200, 0x54faa0, 0xc4203f2570, 0x5ee0c6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/williamthurston/go/src/github.com/blox/blox/vendor/github.com/golang/mock/gomock/controller.go:113 +0x452
github.com/blox/blox/cluster-state-service/handler/mocks.(*MockTaskLoader).LoadTasks(0xc4203f2570, 0x26, 0x0)
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/mocks/taskloader_mocks.go:45 +0x73
github.com/blox/blox/cluster-state-service/handler/reconcile.(*Reconciler).RunOnce(0xc420404d20, 0x0, 0x0)
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/reconcile/reconciler.go:89 +0xbf
github.com/blox/blox/cluster-state-service/handler/reconcile.(*Reconciler).Run.func1(0xc420404d20)
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/reconcile/reconciler.go:69 +0x2f
created by github.com/blox/blox/cluster-state-service/handler/reconcile.(*Reconciler).Run
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/reconcile/reconciler.go:73 +0x1c6
FAIL	github.com/blox/blox/cluster-state-service/handler/reconcile	0.092s
```

**Comment by narehayrapetyan** [comment] 2016-12-07 18:23
Thanks for catching it Will, let me try and reproduce it.

**Comment by narehayrapetyan** [comment] 2016-12-07 19:51
I haven't been able to reproduce it so far, it always works for me.

**Comment by poojamaiya** [comment] 2016-12-07 19:55
I haven't been able to reproduce it either. Will, do you have any additional details here that might help? Thanks!

**Comment by jhspaybar** [comment] 2016-12-12 04:50
I think I found another one.  I'm just running `make` in the cluster-state-service directory.  I don't think I'm doing anything special.

```
=== RUN   TestPollForEventsFirstProcessEventFails
1481518178218014424 [Info] Starting to poll for events from SQS
1481518178218102547 [Info] Starting to poll for events from SQS
1481518178218111932 [Error] Could not process message: {
  Body: "messageBody",
  ReceiptHandle: "receiptHandle"
}: Process event failed
github.com/blox/blox/cluster-state-service/handler/event.TestPollForEventsFirstProcessEventFails
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer_test.go:264
testing.tRunner
	/usr/local/go/src/testing/testing.go:610
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2086
--- PASS: TestPollForEventsFirstProcessEventFails (0.00s)
=== RUN   TestPollForEventsFirstDeleteEventFails
1481518178218216273 [Info] Starting to poll for events from SQS
--- PASS: TestPollForEventsFirstDeleteEventFails (0.00s)
=== RUN   TestPollForEventsReceiveTwoMessages
1481518178218228209 [Error] Could not delete message {
  Body: "messageBody",
  ReceiptHandle: "receiptHandle"
}: Delete event failed
github.com/blox/blox/cluster-state-service/handler/event.TestPollForEventsFirstDeleteEventFails
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer_test.go:293
testing.tRunner
	/usr/local/go/src/testing/testing.go:610
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2086
Could not delete message
github.com/blox/blox/cluster-state-service/handler/event.sqsEventConsumer.deleteEvent
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer.go:184
github.com/blox/blox/cluster-state-service/handler/event.sqsEventConsumer.processMessages
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer.go:152
github.com/blox/blox/cluster-state-service/handler/event.sqsEventConsumer.pollForMessages
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer.go:141
github.com/blox/blox/cluster-state-service/handler/event.sqsEventConsumer.PollForEvents
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer.go:96
github.com/blox/blox/cluster-state-service/handler/event.(*sqsEventConsumer).PollForEvents
	<autogenerated>:4
github.com/blox/blox/cluster-state-service/handler/event.TestPollForEventsFirstDeleteEventFails
	/Users/williamthurston/go/src/github.com/blox/blox/cluster-state-service/handler/event/sqs_consumer_test.go:302
testing.tRunner
	/usr/local/go/src/testing/testing.go:610
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2086
```

**Comment by kylbarnes** [comment] 2016-12-13 20:06
@jhspaybar can we close this issue, or are you still randomly encountering a failing unit test?

**Comment by poojamaiya** [comment] 2016-12-22 20:19
@jhspaybar I'm closing this issue. Please feel free to re-open if you see this happening again. Thanks!

**Closed by poojamaiya** 2016-12-22 20:19 UTC
