### ISSUE TITLE
cluster-state-service task is failing 

### ISSUE THREAD

**Issue by hridyeshpant** [blox/blox#89] opened 2016-12-12 02:11 UTC
Hi ,
I am using AWS installation mentioned in https://github.com/blox/blox/tree/dev/deploy#local-installation.
But after successfully running the service, i am still seeing below error for  bloxoss/cluster-state-service:0.1.0 task is failing with below error :
2016-12-12T02:06:29Z [INFO] Reconciler loading tasks and instances
2016-12-12T02:07:29Z [CRITICAL] Error starting event stream handler: Error bootstrapping: Failed to reconcile. Could not load tasks.: Error loading tasks from data store: Error loading tasks from store: Context deadline is exceeded: context deadline exceeded

Am i missing something here?

All other task are running fine.
docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                     NAMES
00999f64e828        bloxoss/daemon-scheduler:0.1.0   "/daemon-scheduler --"   5 minutes ago       Up 4 minutes        0.0.0.0:32770->2000/tcp   ecs-BloxFramework-1-scheduler-8cb28feefab9e48c5900
ede79b28d18c        quay.io/coreos/etcd:v3.0.13      "/usr/local/bin/etcd "   5 minutes ago       Up 5 minutes        2379-2380/tcp             ecs-BloxFramework-1-etcd-faba859abcfba88e4e00
0c5c1af7f37d        amazon/amazon-ecs-agent:latest   "/agent"                 2 days ago          Up 2 days                                     ecs-agent

**Comment by poojamaiya** [comment] 2016-12-12 17:55
@hridyeshpant My best guess here is that the service is having issues talking to etcd although I'm unable to reproduce it. Are you using the AWS installation or the local setup? Do you have any additional details that you can share that may help us? Thanks!

**Comment by narehayrapetyan** [comment] 2016-12-13 01:47
@hridyeshpant what happens if you kill all the containers (daemon-scheduler, cluster-state and etcd) and restart them?

**Comment by hridyeshpant** [comment] 2016-12-13 03:34
@poojamaiya @narehayrapetyan after cleaning up everything and running CloudFormation again works.
Not sure whet happened first time.
Thanks for your help,

**Comment by hridyeshpant** [comment] 2016-12-13 13:16
@poojamaiya @narehayrapetyan Now i am able to get REST API response, but not getting relevant information about CPU/Memory
v1/instances 

"clusterARN": "arn:aws:ecs:us-west-2:***:cluster/jenkins",
 "containerInstanceARN": "arn:aws:ecs:us-west-2:***:container-instance/59be2d75-e7ed-413b-94e4-046e13aff649",
      "registeredResources": [
        {
          "name": "CPU",
          "type": "INTEGER",
          "value": "0.00"
        },
        {
          "name": "MEMORY",
          "type": "INTEGER",
          "value": "0.00"
        },
        {
          "name": "PORTS",
          "type": "STRINGSET",
          "value": "0.00"
        },
        {
          "name": "PORTS_UDP",
          "type": "STRINGSET",
          "value": "0.00"
        }
      ],
,
      "status": "ACTIVE",
      "versionInfo": {
        "agentHash": "efe53c6",
        "agentVersion": "1.13.1",
        "dockerVersion": "DockerVersion: 1.11.2"
      }

**Comment by poojamaiya** [comment] 2016-12-13 19:29
@hridyeshpant This indeed does look like a bug on our end. Thanks for reporting it. I've created an issue #97 to track this. We'd like to close this issue in favor of the new issue tracking the bug. Please feel free to re-open this or create a new one if you have any more questions.

**Closed** 2016-12-13 19:39 UTC
